/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 邮箱注册 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RegisterRequest"];
                };
            };
            responses: {
                /** @description 注册成功 */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"] & {
                            data?: components["schemas"]["AuthTokens"];
                        };
                    };
                };
                /** @description 参数校验失败 */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 邮箱已存在 */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 邮箱密码登录 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginRequest"];
                };
            };
            responses: {
                /** @description 登录成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"] & {
                            data?: components["schemas"]["AuthTokens"];
                        };
                    };
                };
                /** @description 邮箱或密码错误 */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/oauth/{provider}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** OAuth 登录跳转 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    provider: "google" | "apple" | "facebook";
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 重定向到 OAuth 提供商 */
                302: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/oauth/{provider}/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** OAuth 回调 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    provider: "google" | "apple" | "facebook";
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @description OAuth 授权码 */
                        code: string;
                    };
                };
            };
            responses: {
                /** @description 登录成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"] & {
                            data?: components["schemas"]["AuthTokens"];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 刷新 Token */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RefreshTokenRequest"];
                };
            };
            responses: {
                /** @description 刷新成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"] & {
                            data?: components["schemas"]["AuthTokens"];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 登出 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 登出成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dramas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 短剧列表（含推荐/分类筛选） */
        get: {
            parameters: {
                query?: {
                    category_id?: number;
                    sort?: "latest" | "popular" | "trending";
                    keyword?: string;
                    /** @description 逗号分隔 */
                    tags?: string;
                    page?: number;
                    page_size?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 短剧列表 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"] & {
                            data?: components["schemas"]["Drama"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dramas/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 短剧详情 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 短剧详情 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"] & {
                            data?: components["schemas"]["Drama"];
                        };
                    };
                };
                /** @description 短剧不存在 */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dramas/{id}/episodes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 剧集列表 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 剧集列表 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"] & {
                            data?: components["schemas"]["Episode"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/episodes/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 剧集详情含播放地址 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 剧集详情 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"] & {
                            data?: components["schemas"]["Episode"];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/episodes/{id}/play": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取播放 URL（签名） */
        get: {
            parameters: {
                query?: {
                    quality?: "1080p" | "720p" | "480p";
                    language?: string;
                };
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 播放信息 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"] & {
                            data?: components["schemas"]["EpisodePlayInfo"];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/favorites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 收藏列表 */
        get: {
            parameters: {
                query?: {
                    page?: number;
                    page_size?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 收藏列表 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"] & {
                            data?: components["schemas"]["Favorite"][];
                        };
                    };
                };
            };
        };
        put?: never;
        /** 添加收藏 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AddFavoriteRequest"];
                };
            };
            responses: {
                /** @description 收藏成功 */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 已收藏 */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/favorites/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** 取消收藏 */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 取消收藏成功 */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 收藏不存在 */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dramas/{id}/comments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 评论列表 */
        get: {
            parameters: {
                query?: {
                    sort?: "latest" | "hottest";
                    page?: number;
                    page_size?: number;
                };
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 评论列表 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"] & {
                            data?: components["schemas"]["Comment"][];
                        };
                    };
                };
            };
        };
        put?: never;
        /** 发布评论 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateCommentRequest"];
                };
            };
            responses: {
                /** @description 评论成功 */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/comments/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** 删除评论 */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 删除成功 */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 无权限 */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/comments/{id}/like": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 点赞评论 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 操作成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"] & {
                            data?: {
                                is_liked?: boolean;
                                likes_count?: number;
                            };
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/subscriptions/plans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 订阅计划列表 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 计划列表 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"] & {
                            data?: components["schemas"]["SubscriptionPlan"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/subscriptions/create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 创建订阅 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateSubscriptionRequest"];
                };
            };
            responses: {
                /** @description 创建成功，返回支付链接 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"] & {
                            data?: {
                                subscription_id?: number;
                                /** Format: uri */
                                payment_url?: string;
                            };
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/subscriptions/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 取消订阅 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 取消成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/subscriptions/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 订阅状态 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 订阅状态 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"] & {
                            data?: components["schemas"]["Subscription"];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/payments/webhook/{channel}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 支付回调 Webhook */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    channel: "paypal" | "stripe" | "apple" | "google";
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": unknown;
                };
            };
            responses: {
                /** @description 回调处理成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ApiResponse: {
            /**
             * @description 0=成功, 非0=错误码
             * @example 0
             */
            code?: number;
            /** @example success */
            message?: string;
            data?: Record<string, never> | null;
            meta?: {
                /** @example 1 */
                page?: number;
                /** @example 20 */
                page_size?: number;
                /** @example 150 */
                total?: number;
            } | null;
        };
        PaginationParams: {
            /** @default 1 */
            page: number;
            /** @default 20 */
            page_size: number;
        };
        User: {
            /** Format: int64 */
            id?: number;
            /** Format: email */
            email?: string;
            nickname?: string;
            /** Format: uri */
            avatar_url?: string;
            /** @enum {string} */
            role?: "user" | "creator" | "admin" | "superadmin";
            language?: string;
            region?: string;
            /** Format: date-time */
            created_at?: string;
        };
        RegisterRequest: {
            /** Format: email */
            email: string;
            password: string;
            nickname: string;
        };
        LoginRequest: {
            /** Format: email */
            email: string;
            password: string;
        };
        AuthTokens: {
            /** @description JWT Access Token (15min 有效期) */
            access_token?: string;
            /** @description Refresh Token (30天 有效期) */
            refresh_token?: string;
            /**
             * @description Access Token 过期秒数
             * @example 900
             */
            expires_in?: number;
            user?: components["schemas"]["User"];
        };
        RefreshTokenRequest: {
            refresh_token: string;
        };
        Drama: {
            /** Format: int64 */
            id?: number;
            title?: string;
            description?: string;
            /** Format: uri */
            cover_url?: string;
            category_id?: number;
            creator?: components["schemas"]["User"];
            total_episodes?: number;
            /** @enum {string} */
            status?: "draft" | "published" | "reviewing" | "archived";
            tags?: string[];
            /** Format: date-time */
            release_at?: string;
            /** Format: date-time */
            created_at?: string;
            /** @description 播放次数 */
            view_count?: number;
            like_count?: number;
            favorite_count?: number;
        };
        DramaListParams: {
            category_id?: number;
            /** @enum {string} */
            status?: "draft" | "published" | "reviewing" | "archived";
            /**
             * @default latest
             * @enum {string}
             */
            sort: "latest" | "popular" | "trending";
            /** @description 逗号分隔的标签 */
            tags?: string;
            keyword?: string;
        };
        Episode: {
            /** Format: int64 */
            id?: number;
            /** Format: int64 */
            drama_id?: number;
            episode_no?: number;
            title?: string;
            /** @description 时长（秒） */
            duration?: number;
            /** Format: uri */
            video_url?: string;
            /** @enum {string} */
            status?: "processing" | "ready" | "failed";
            localizations?: components["schemas"]["Localization"][];
            /** Format: date-time */
            created_at?: string;
        };
        EpisodePlayInfo: {
            episode?: components["schemas"]["Episode"];
            /**
             * Format: uri
             * @description 签名后的播放 URL
             */
            play_url?: string;
            /** Format: date-time */
            expires_at?: string;
            qualities?: components["schemas"]["VideoQuality"][];
        };
        VideoQuality: {
            /** @example 720p */
            resolution?: string;
            /** Format: uri */
            url?: string;
            /** @description kbps */
            bitrate?: number;
        };
        Localization: {
            /** Format: int64 */
            id?: number;
            /** Format: int64 */
            episode_id?: number;
            language?: string;
            title_translated?: string;
            /** Format: uri */
            dub_url?: string;
            /** Format: uri */
            subtitle_url?: string;
            /** Format: uri */
            lip_sync_url?: string;
            /** @enum {string} */
            status?: "pending" | "processing" | "completed" | "failed";
        };
        Favorite: {
            /** Format: int64 */
            id?: number;
            /** Format: int64 */
            user_id?: number;
            /** Format: int64 */
            drama_id?: number;
            drama?: components["schemas"]["Drama"];
            /** Format: date-time */
            created_at?: string;
        };
        AddFavoriteRequest: {
            /** Format: int64 */
            drama_id: number;
        };
        Comment: {
            /** Format: int64 */
            id?: number;
            user?: components["schemas"]["User"];
            /** Format: int64 */
            drama_id?: number;
            /** Format: int64 */
            parent_id?: number | null;
            content?: string;
            likes_count?: number;
            /** @description 当前用户是否已点赞 */
            is_liked?: boolean;
            /** Format: date-time */
            created_at?: string;
        };
        CreateCommentRequest: {
            content: string;
            /**
             * Format: int64
             * @description 回复评论时传入父评论 ID
             */
            parent_id?: number;
        };
        SubscriptionPlan: {
            id?: number;
            /** @enum {string} */
            name?: "monthly" | "quarterly" | "yearly";
            /** Format: float */
            price?: number;
            /** @default USD */
            currency: string;
            description?: string;
            features?: string[];
        };
        Subscription: {
            /** Format: int64 */
            id?: number;
            /** Format: int64 */
            user_id?: number;
            /** @enum {string} */
            plan_type?: "monthly" | "quarterly" | "yearly";
            /** Format: date-time */
            start_at?: string;
            /** Format: date-time */
            end_at?: string;
            /** @enum {string} */
            status?: "active" | "cancelled" | "expired";
            auto_renew?: boolean;
        };
        CreateSubscriptionRequest: {
            /** @enum {string} */
            plan_type: "monthly" | "quarterly" | "yearly";
            /** @enum {string} */
            channel: "paypal" | "stripe" | "apple_pay" | "google_pay";
            /**
             * Format: uri
             * @description 支付成功后跳转 URL
             */
            return_url?: string;
        };
        ApiError: {
            code?: number;
            message?: string;
            details?: Record<string, never> | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
